---

version: '3'

services:
  elasticsearch-1:
    build: elasticsearch/.
    hostname: elasticsearch-1
    container_name: elasticsearch-1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    build: kibana/.
    hostname: kibana
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-1:9200
    ports:
      - 5601:5601

  logstash:
    build: logstash
    hostname: logstash
    container_name: logstash
    environment:
      - "xpack.monitoring.elasticsearch.url=http://elasticsearch-1:9200"
