---

version: '3'

services:
  elasticsearch:
    build: elasticsearch/.
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  es-data-1:
    build: elasticsearch/.
    hostname: es-data-1
    container_name: es-data-1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/elasticsearch.data1.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  es-data-2:
    build: elasticsearch/.
    hostname: es-data-2
    container_name: es-data-2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/elasticsearch.data2.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    build: kibana/.
    hostname: kibana
    container_name: kibana
    ports:
      - 5601:5601
