---

version: '3'

services:
  elasticsearch-1:
    build: elasticsearch/.
    hostname: elasticsearch-1
    container_name: elasticsearch-1

  kibana:
    build: kibana/.
    hostname: kibana
    container_name: kibana

  logstash:
    build: logstash
    hostname: logstash
    container_name: logstash
