---

version: '3'

services:
  elasticsearch:
    build: elasticsearch/.
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  es-data-1:
    build: elasticsearch/.
    hostname: es-data-1
    container_name: es-data-1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/elasticsearch.data.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    build: kibana/.
    hostname: kibana
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601

  logstash:
    build: logstash
    hostname: logstash
    container_name: logstash
    volumes:
      - ./logstash/es-logs.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
